name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  gradle:
    # Job name is Greeting
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: asciidoc
